# Generated by Django 5.2.9 on 2026-01-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='page',
            name='is_show_footer',
            field=models.BooleanField(default=False, verbose_name='Mostrar en el pie de pagina'),
        ),
    ]
