# Generated by Django 5.2.9 on 2026-01-20 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_is_active_page_is_show_footer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='is_show_footer',
            new_name='show_in_footer',
        ),
    ]
