# Generated by Django 5.2.9 on 2026-01-22 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_is_show_footer_page_show_in_footer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title'], 'verbose_name': 'Pagina', 'verbose_name_plural': 'Paginas'},
        ),
    ]
