# Generated by Django 5.2.9 on 2026-01-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado'), ('deleted', 'Eliminado')], default='draft', max_length=10),
        ),
    ]
