# Generated by Django 5.2.9 on 2026-01-22 04:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-created'], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, help_text='Descripcion corta del autor', verbose_name='Biografia'),
        ),
        migrations.AddField(
            model_name='author',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='github',
            field=models.CharField(blank=True, help_text='Solo el nombre de usuario', max_length=50, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='author',
            name='is_site_author',
            field=models.BooleanField(default=False, help_text='Solo puede haber uno marcado como principal', verbose_name='Autor principal del sitio'),
        ),
        migrations.AddField(
            model_name='author',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='Linkedin'),
        ),
        migrations.AddField(
            model_name='author',
            name='twitter',
            field=models.CharField(blank=True, help_text='Solo el nombre de usuario', max_length=50, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='author',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion'),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_profile', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='author',
            name='website',
            field=models.URLField(blank=True, help_text='Url complet (htpps://...)', verbose_name='Sitio web'),
        ),
    ]
